"""Bounded ports of incumbent rectangular site, cost and utilization scenarios."""

import math

from .workspace import Site, Costs


# Source parity: index.html T3 and compute; no new regulatory interpretation.
COMMON_FRONT = (3, 4, 5, 6, 7.5)
BANDS = (
    (50, ((7, (1.5, 1.5, 3, 3, 3), 0),)),
    (100, ((7, (1.5, 1.5, 3, 3, 3), 0), (10, (1.5, 1.5, 3, 3, 3), .5))),
    (200, ((10, (1.5, 1.5, 3, 3, 3), 1),)),
    (300, ((7, (2, 3, 3, 4, 5), 1), (10, (2, 3, 3, 5, 6), 1.5))),
    (400, ((7, COMMON_FRONT, 1.5), (12, COMMON_FRONT, 2))),
    (500, ((7, COMMON_FRONT, 2), (12, COMMON_FRONT, 2.5))),
    (750, ((7, COMMON_FRONT, 2.5), (12, COMMON_FRONT, 3), (15, COMMON_FRONT, 3.5))),
    (1000, ((7, COMMON_FRONT, 3), (12, COMMON_FRONT, 3.5), (15, COMMON_FRONT, 4))),
    (1500, ((7, COMMON_FRONT, 3.5), (12, COMMON_FRONT, 4), (15, COMMON_FRONT, 5), (18, COMMON_FRONT, 6))),
    (2500, ((7, COMMON_FRONT, 4), (15, COMMON_FRONT, 5), (18, COMMON_FRONT, 6))),
    (math.inf, ((7, COMMON_FRONT, 5), (15, COMMON_FRONT, 6), (18, COMMON_FRONT, 7))),
)
SOURCES = [
    {"title": "G.O.Ms.No.168 (2012): retained Table II/III rules", "url": "https://lrsbrs.hmda.gov.in/hmdaLMS/data/168.pdf"},
    {"title": "BuildNow current GOs and Acts: verify amendments", "url": "https://buildnow.telangana.gov.in/go-and-act/"},
    {"title": "TG-bPASS: confirm applicable permission route", "url": "https://tgbpass.telangana.gov.in/"},
]
SCOPE = (
    "Port of incumbent rectangular Table III/IV and GO 95 scenarios, not permission or a surveyed plan. "
    "Retained published schedules require current amendment, land-use, access, parking and fire review. "
    "No room layout is generated by a site scenario."
)
HIGH_RISE = ((21, 12, 7), (24, 12, 8), (27, 18, 9), (30, 18, 10),
             (35, 24, 11), (40, 24, 12), (45, 24, 13), (50, 30, 14), (55, 30, 16))


def road_limits(road, category):
    effective = max(9, road)
    height = (10 if category == "A" else 12) if road < 9 else (
        15 if effective < 12 else 24 if effective < 18 else 30 if effective < 24 else 45 if effective < 30 else 999)
    floors = (3 if category == "A" else 4) if road < 9 else 5 if effective < 12 else 6 if effective < 18 else 99
    band = next(i for i, upper in enumerate((12, 18, 24, 30, math.inf)) if effective <= upper)
    return effective, height, floors, band


def tdr_floors(area, road, enabled):
    return (5 if road >= 24 else 4 if road >= 18 else 3 if road >= 12 else 0) if enabled and area > 2000 else 0


def custom_setbacks(site):
    return {role: getattr(site, f"setback_{role}_m") for role in ("front", "rear", "left", "right")} if site.custom_setbacks else None


def height_choices(area, road, category, tdr):
    effective, cap_height, _, _ = road_limits(road, category)
    rows = next(rows for upper, rows in BANDS if area <= upper)
    allowed = [row[0] for row in rows if row[0] <= cap_height and (row[0] != 18 or effective >= 12)]
    if tdr and 750 <= area <= 2000 and cap_height >= 20:
        allowed.append(20)
    if area >= 2000:
        allowed += [height for height, min_road, _ in HIGH_RISE if min_road <= effective and height <= cap_height]
    return allowed


def plot_options(site):
    if site.width is None or site.depth is None or any(site.roads[edge] is None for edge in site.facing):
        return {"heights": [], "max_floors": None, "message": "Enter plot dimensions and every abutting road width to see applicable bands."}
    front = next(edge for edge in "ENWS" if edge in site.facing)
    road = site.roads[front]
    factor = .3048 if site.units == "ft" else 1
    strip = max(0, 4.5-road/2)
    width = max(0, site.width*factor-(strip if front in "EW" else 0))
    depth = max(0, site.depth*factor-(strip if front in "NS" else 0))
    area = width*depth
    if area <= 0:
        return {"heights": [], "max_floors": None, "message": "Road widening consumes the plot."}
    heights = height_choices(area, road, site.category, site.tdr)
    maximum = None
    if site.height_m in heights and site.floor_height_m is not None:
        effective, _, cap_floors, _ = road_limits(road, site.category)
        maximum = min(math.floor(site.height_m/site.floor_height_m+1e-9),cap_floors)+tdr_floors(area,effective,site.tdr)
    return {"heights": heights, "max_floors": maximum, "message": "Applicable draft bands; nothing saved. Apply explicitly after reviewing your selection."}


def feasibility(site: Site):
    missing = [name for name in ("width", "depth", "height_m", "floor_height_m") if getattr(site, name) is None]
    edges = list(site.facing)
    missing += [f"{edge} road width" for edge in edges if site.roads[edge] is None]
    if site.custom_setbacks:
        missing += [f"{role} custom setback" for role, value in custom_setbacks(site).items() if value is None]
    if missing:
        return {"status": "prerequisites", "messages": ["Supply " + ", ".join(missing)], "scope": SCOPE}
    factor = .3048 if site.units == "ft" else 1
    width, depth = site.width * factor, site.depth * factor
    front = next(edge for edge in "ENWS" if edge in edges)
    road = site.roads[front]
    strip = max(0, 4.5 - road / 2) if road < 9 else 0
    net_width = max(0, width - (strip if front in "EW" else 0))
    net_depth = max(0, depth - (strip if front in "NS" else 0))
    area = net_width * net_depth
    if area <= 0:
        return {"status": "infeasible", "messages": ["Road widening consumes the plot."], "scope": SCOPE}
    effective_road, cap_height, cap_floors, road_band = road_limits(road, site.category)
    rows = next(rows for upper, rows in BANDS if area <= upper)
    allowed_heights = height_choices(area, road, site.category, site.tdr)
    if site.height_m not in allowed_heights:
        return {"status": "prerequisites", "messages": ["Select an applicable height band: " + ", ".join(map(str, allowed_heights)) + " m."],
                "allowed_heights": allowed_heights, "scope": SCOPE}
    high_rise = site.height_m >= 21
    tdr_band = 18 < site.height_m < 21
    row = next((row for row in rows if row[0] == site.height_m), rows[-1])
    side, front_setback = row[2], row[1][road_band]
    if high_rise:
        side = next(sb for height, _, sb in HIGH_RISE if site.height_m <= height)
        side = max(7, side * .9) if site.tdr else side
        front_setback = max(side, COMMON_FRONT[road_band])
    required = dict.fromkeys("NESW", side)
    required[front] = front_setback
    setbacks = dict(required)
    if site.custom_setbacks:
        rotation = {"N": ("N", "E", "S", "W"), "E": ("E", "S", "W", "N"),
                    "S": ("S", "W", "N", "E"), "W": ("W", "N", "E", "S")}[front]
        setbacks = dict(zip(rotation, (site.setback_front_m, site.setback_right_m, site.setback_rear_m, site.setback_left_m)))
    violations = [edge for edge in "NESW" if setbacks[edge] < required[edge] - 1e-7]
    bw = max(0, net_width - setbacks["W"] - setbacks["E"])
    bd = max(0, net_depth - setbacks["N"] - setbacks["S"])
    footprint = bw * bd
    open_area = area * (.1 if high_rise else .05 if area > 750 else 0)
    usable = max(0, footprint - open_area)
    extra = tdr_floors(area, effective_road, site.tdr)
    maximum = min(math.floor(site.height_m / site.floor_height_m + 1e-9), cap_floors) + extra
    if maximum < 1 or (site.floors is not None and site.floors > maximum):
        return {"status": "prerequisites", "messages": [f"Select between 1 and {maximum} planned floors."], "scope": SCOPE}
    floors = maximum if site.floors is None else site.floors
    net_x, net_y = (strip if front == "W" else 0), (strip if front == "N" else 0)
    messages = [SCOPE, "Scenario floors do not create editable storeys."]
    compound = site.compounding and not high_rise and not site.custom_setbacks
    compounded = {edge: value if edge == front else value * .9 for edge, value in required.items()}
    compound_area = max(0, max(0, net_width - compounded["W"] - compounded["E"]) *
                        max(0, net_depth - compounded["N"] - compounded["S"]) - open_area) if compound else usable
    if violations:
        messages.append("Non-compliant custom setback scenario: below retained minima on " + ", ".join(violations) + ". Not permission to construct.")
    if tdr_band:
        messages.append("GO 95 does not restate setbacks for the 18–21 m TDR band; tallest Table III row is the retained interpretation. Confirm with TG-bPASS.")
    if site.compounding:
        messages.append("Compounding is a separate discretionary post-facto scenario, not a design entitlement." if compound
                        else "Compounding is disabled for high-rise or custom-setback scenarios.")
    if site.tdr:
        messages.append("TDR benefits depend on qualifying entitlement; acquisition cost is not inferred.")
    if len(edges) > 1:
        messages.append(f"Incumbent corner-front election: {front}; verify wider-road access and required junction splay.")
    if road < 9:
        messages.append("Road widening uses the incumbent centreline assumption, not a surveyed reservation. No relaxations.")
        if site.use != "res" and site.category == "B":
            messages.append("Sub-9 m Category B road height allowance is for individual residential use; selected use needs authority review.")
    return {
        "status": "computed" if usable > 0 else "infeasible", "scope": SCOPE, "messages": messages,
        "allowed_heights": allowed_heights, "gross_area_m2": width * depth, "net_area_m2": area,
        "widening_m": strip, "front": front, "setbacks_m": setbacks,
        "required_setbacks_m": required, "non_compliant": bool(violations), "setback_violations": violations,
        "high_rise": high_rise, "tdr_band": tdr_band, "tdr_extra_floors": extra,
        "compounding_active": compound, "compounded_usable_m2": compound_area,
        "compounding_gain_m2": max(0, compound_area - usable),
        "effective_road_m": effective_road, "road_height_cap_m": cap_height,
        "road_floor_cap": cap_floors, "road_band": road_band,
        "gross": {"x": 0, "y": 0, "width": width, "depth": depth},
        "net": {"x": net_x, "y": net_y, "width": net_width, "depth": net_depth},
        "envelope": {"x": net_x + setbacks["W"], "y": net_y + setbacks["N"], "width": bw, "depth": bd},
        "footprint_m2": footprint, "open_space_m2": open_area, "usable_m2": usable,
        "coverage_percent": usable / area * 100, "lost_percent": 100 - usable / area * 100,
        "max_floors": maximum, "floors": floors, "built_up_m2": usable * floors,
        "parking_required_m2": usable * floors * (.4 if site.use == "com" else .3),
        "parking_basis": "Retained Table V GHMC percentage of scenario built-up area, not a vehicle/access layout.",
    }


def cost_estimate(site: Site, costs: Costs):
    plan = feasibility(site)
    if plan["status"] != "computed":
        return {"status": "prerequisites", "messages": ["Apply a computable Site scenario before estimating costs."]}
    required = ["land_inr_m2", "construction_inr_m2", "land_sro_inr_m2", "registration_percent", "gst_percent"]
    if site.stilt and costs.stilt_rate_mode == "explicit":
        required.append("stilt_inr_m2")
    full = costs.estimate_scope == "legacy-schedule"
    if full:
        required += ["lrs_mode", "brs_mode"]
        if costs.lrs_mode == "due":
            required.append("lrs_rebate")
        if costs.brs_mode in {"dev", "unauth"}:
            required.append("brs_violated_m2")
    missing = [key for key in required if getattr(costs, key) is None]
    if missing:
        return {"status": "prerequisites", "messages": ["Supply cost inputs: " + ", ".join(missing)]}
    footprint = plan["compounded_usable_m2"] if plan["compounding_active"] else plan["usable_m2"]
    built = footprint * plan["floors"]
    construction = built * costs.construction_inr_m2
    stilt_rate = costs.stilt_inr_m2 if costs.stilt_rate_mode == "explicit" else (
        math.floor(costs.construction_inr_m2 * .09290304 * .55 + .5) / .09290304)
    stilt = footprint * stilt_rate if site.stilt else 0
    lines = {
        "Land purchase": plan["gross_area_m2"] * costs.land_inr_m2,
        "Registration at supplied rate": plan["gross_area_m2"] * costs.land_sro_inr_m2 * costs.registration_percent / 100,
        "Construction": construction, "Stilt": stilt,
        "GST at supplied rate": (construction + stilt) * costs.gst_percent / 100,
    }
    messages = ["Partial supplied-rate estimate, not an all-in quote. Statutory schedules are excluded until explicitly selected."]
    details = {}
    if full:
        details = schedule_charges(site, costs, plan, footprint, built, construction + stilt)
        lines.update(details.pop("lines_inr"))
        messages = [
            "Retained-schedule estimate, not an all-in quote or a statement of current tax/legal eligibility.",
            "LRS: GO 131/135 (2020), gross plot area and SRO land bands plus 14% open-space shortfall; the optional 25% rebate requires independently confirmed eligibility.",
            "BRS: legacy GO 152/2015 post-facto scenario, distinct from TG-bPASS pre-construction permission. Due BRS subsumes betterment and impact here; do not levy them twice.",
            "Betterment: GHMC 2008 schedule (125 residential / 175 commercial INR/m²). Impact: GO 168 Table VI, first 15 m excluded. Current revisions must be checked.",
            "Cess: incumbent 1% model, commercial always or construction exceeding INR 5,000,000. Confirm applicability; no eligibility inferred for apartment or individual projects.",
            "TDR acquisition, permit/scrutiny fees and other unmodelled charges are not included. Already-paid LRS/BRS are excluded, not refunded.",
        ]
    if costs.stilt_rate_mode == "legacy-55-percent":
        messages.append("Explicitly selected legacy stilt assumption: 55% of construction INR/ft², rounded to the nearest whole rupee before conversion.")
    if plan["compounding_active"]:
        messages.append("Construction uses the separate compounded footprint; Rule 26(d) relief is discretionary. Its land-value fee is included only in retained-schedule mode.")
    if plan["non_compliant"]:
        messages.append("Non-compliant custom setbacks are included in this cost scenario. A cost estimate does not establish permission or regularisation eligibility.")
    fmt = lambda value: f"{value:,.4f}".rstrip("0").rstrip(".")
    basis = {
        "Land purchase": f"{fmt(plan['gross_area_m2'] / .83612736)} sq yd gross registered plot × {fmt(costs.land_inr_m2 * .83612736)} INR/sq yd; includes any widening strip.",
        "Registration at supplied rate": f"{fmt(costs.registration_percent)}% × {fmt(plan['gross_area_m2'] / .83612736)} sq yd gross plot × {fmt(costs.land_sro_inr_m2 * .83612736)} INR/sq yd land SRO (not purchase price).",
        "Construction": f"{fmt(built / .09290304)} sq ft usable built-up × {fmt(costs.construction_inr_m2 * .09290304)} INR/sq ft; {plan['floors']} scenario floors.",
        "Stilt": f"{fmt(footprint / .09290304)} sq ft × {fmt(stilt_rate * .09290304)} INR/sq ft; excluded from habitable built-up." if site.stilt else "No stilt selected in the applied Site scenario.",
        "GST at supplied rate": f"{fmt(costs.gst_percent)}% of construction plus stilt. Confirm the applicable transaction rate.",
    }
    states = {"Stilt": "included" if site.stilt else "not-selected"}
    if full:
        basis.update({
            "LRS regularisation": (
                f"{fmt(plan['gross_area_m2'])} m² × {fmt(details['lrs_basic_inr_m2'])} INR/m² × {fmt(details['sro_band_percent'])}% SRO band, "
                f"plus 14% of gross land SRO; {25 if costs.lrs_rebate else 0}% selected rebate. Retained GO 131/135 (2020)."
                if costs.lrs_mode == "due" else "Already paid: excluded, not refunded." if costs.lrs_mode == "paid" else "Not applicable as declared by the user; not verified."),
            "BRS regularisation": (
                f"{fmt(costs.brs_violated_m2 / .09290304)} sq ft violated built-up × {fmt(details['brs_basic_inr_ft2'])} INR/sq ft × {fmt(details['sro_band_percent'])}% SRO band. "
                "Retained GO 152/2015; includes betterment and impact in this model."
                if costs.brs_mode in {"dev", "unauth"} else "Already paid: excluded, not refunded." if costs.brs_mode == "paid" else "Not applicable as declared by the user; not verified."),
            "Betterment (included in BRS when due)": "Subsumed in due BRS; not charged a second time." if details["brs_subsumes_betterment_impact"] else f"{fmt(built)} m² built-up × {175 if site.use == 'com' else 125} INR/m². GHMC 2008 schedule; current revisions unverified.",
            "Infrastructure impact (included in BRS when due)": "Subsumed in due BRS; not charged a second time." if details["brs_subsumes_betterment_impact"] else f"{details['chargeable_floors_above_15m']} floors above the first 15 m × {fmt(footprint)} m² × {details['impact_rate_inr_m2']} INR/m². GO 168 Table VI.",
            "Labour cess": "Retained 1% of construction plus stilt: commercial or construction exceeding INR 5,000,000. Current eligibility unverified.",
            "Rule 26(d) compounding": f"{fmt(plan['compounding_gain_m2'] / .83612736)} sq yd additional footprint × {fmt(costs.land_sro_inr_m2 * .83612736)} INR/sq yd land SRO; discretionary post-facto scenario." if plan["compounding_active"] else "No active compounding scenario; not charged.",
        })
        states.update({
            "LRS regularisation": {"paid": "already-paid", "na": "not-applicable", "due": "included"}[costs.lrs_mode],
            "BRS regularisation": {"paid": "already-paid", "na": "not-applicable", "dev": "included", "unauth": "included"}[costs.brs_mode],
            "Betterment (included in BRS when due)": "included-in-BRS" if details["brs_subsumes_betterment_impact"] else "included",
            "Infrastructure impact (included in BRS when due)": "included-in-BRS" if details["brs_subsumes_betterment_impact"] else "included",
            "Rule 26(d) compounding": "included" if plan["compounding_active"] else "not-selected",
        })
    total = sum(lines.values())
    return {"status": "computed", "lines_inr": lines, "subtotal_inr": total,
            "estimate_scope": costs.estimate_scope, "non_compliant": plan["non_compliant"],
            "line_items": [{"label": label, "amount_inr": amount, "state": states.get(label, "included"), "basis": basis[label]}
                           for label, amount in lines.items()],
            "costed_footprint_m2": footprint, "costed_built_up_m2": built,
            "inr_per_built_m2": total / built if built > 0 else None,
            "inr_per_built_ft2": total / (built / .09290304) if built > 0 else None,
            "onward_sale_sro_inr": built * costs.flat_sro_inr_m2 if costs.flat_sro_inr_m2 is not None else None,
            "onward_sale_duty_inr": built * costs.flat_sro_inr_m2 * costs.registration_percent / 100 if costs.flat_sro_inr_m2 is not None else None,
            "onward_sale_basis": "Informational only; not included in subtotal. Blank flat SRO remains unknown.",
            "schedule_details": details, "messages": messages}


def pick_row(rows, value):
    return next((row for row in rows if value <= row[0]), rows[-1])


def schedule_charges(site, costs, plan, footprint, built, construction):
    gross = plan["gross_area_m2"]
    sro = gross * costs.land_sro_inr_m2
    sro_sqyd = costs.land_sro_inr_m2 * .83612736
    percent = pick_row(((3000, 20), (5000, 30), (10000, 40), (20000, 50),
                        (30000, 60), (50000, 80), (math.inf, 100)), sro_sqyd)[1]
    basic = pick_row(((100, 200), (300, 400), (500, 600), (math.inf, 750)), gross)[1]
    lrs = (gross * basic * percent / 100 + sro * .14) * (.75 if costs.lrs_rebate else 1) if costs.lrs_mode == "due" else 0
    # (area upper bound, deviation residential/commercial, unauthorised residential/commercial)
    brs_row = pick_row(((100, 15, 30, 15, 30), (300, 30, 60, 30, 60), (500, 60, 120, 100, 200),
                        (1000, 100, 200, 120, 250), (math.inf, 150, 300, 200, 400)), gross)
    is_com = site.use == "com"
    brs_due = costs.brs_mode in {"dev", "unauth"}
    brs_rate = brs_row[(3 if costs.brs_mode == "unauth" else 1) + int(is_com)] if brs_due else 0
    brs = costs.brs_violated_m2 / .09290304 * brs_rate * percent / 100 if brs_due else 0
    charge_floors = max(0, plan["floors"] - math.floor(15 / site.floor_height_m + 1e-9))
    impact_row = pick_row(((7, 500, 1000), (10, 750, 1500), (17, 1500, 2500), (math.inf, 3000, 5000)), plan["floors"])
    impact = footprint * charge_floors * impact_row[2 if is_com else 1]
    betterment = built * (175 if is_com else 125)
    cess = construction * .01 if is_com or construction > 5000000 else 0
    fine = plan["compounding_gain_m2"] * costs.land_sro_inr_m2 if plan["compounding_active"] else 0
    return {"lines_inr": {"LRS regularisation": lrs, "BRS regularisation": brs,
                         "Betterment (included in BRS when due)": 0 if brs_due else betterment,
                         "Infrastructure impact (included in BRS when due)": 0 if brs_due else impact,
                         "Labour cess": cess, "Rule 26(d) compounding": fine},
            "lrs_basic_inr_m2": basic, "sro_band_percent": percent, "brs_basic_inr_ft2": brs_rate,
            "impact_rate_inr_m2": impact_row[2 if is_com else 1],
            "brs_subsumes_betterment_impact": brs_due, "chargeable_floors_above_15m": charge_floors}


def comparison_envelope(frontage, depth, road, site, *, deduct_widening=True, sensitivity=False):
    effective, cap_height, cap_floors, band_index = road_limits(road, site.category)
    net_depth = max(0, depth - (max(0, 4.5 - road / 2) if road < 9 and deduct_widening else 0))
    area = frontage * net_depth
    rows = next(rows for upper, rows in BANDS if area <= upper)
    available = [row for row in rows if row[0] <= cap_height and (row[0] != 18 or effective >= 12)]
    row = available[-1] if available else rows[0]
    required = {"front": row[1][band_index], "rear": row[2], "left": row[2], "right": row[2]}
    applied = custom_setbacks(site) or dict(required)
    if sensitivity and site.compounding and not site.custom_setbacks:
        applied = {key: value if key == "front" else value * .9 for key, value in required.items()}
    open_area = area * .05 if area > 750 else 0
    usable = max(0, max(0, frontage - applied["left"] - applied["right"]) *
                 max(0, net_depth - applied["front"] - applied["rear"]) - open_area)
    base = max(0, max(0, frontage - 2 * row[2]) * max(0, net_depth - row[1][band_index] - row[2]) - open_area)
    maximum = min(math.floor(row[0] / site.floor_height_m + 1e-9), cap_floors)
    if sensitivity:
        maximum += tdr_floors(area, effective, site.tdr)
    floors = maximum if site.floors is None else min(maximum, site.floors)
    widening = depth - net_depth
    return {"frontage_m": frontage, "gross_depth_m": depth, "depth_m": net_depth,
            "widening_m": widening,
            "envelope": {"x": applied["left"], "y": widening + applied["front"],
                         "width": max(0, frontage - applied["left"] - applied["right"]),
                         "depth": max(0, net_depth - applied["front"] - applied["rear"])},
            "net_area_m2": area, "height_m": row[0],
            "required_setbacks_m": required, "applied_setbacks_m": applied,
            "non_compliant": any(applied[key] < required[key] - 1e-7 for key in required),
            "usable_m2": usable, "max_floors": maximum, "floors": floors, "built_up_m2": usable * floors,
            "lost_percent": (1 - usable / area) * 100 if area else 0,
            "built_up_per_net_m2": usable * floors / area if area else 0,
            "compounding_gain_m2": max(0, usable - base)}


def split_pair(frontage, depth, fraction, road, site):
    a = comparison_envelope(frontage * fraction, depth, road, site)
    b = comparison_envelope(frontage - frontage * fraction, depth, road, site)
    area, usable = a["net_area_m2"] + b["net_area_m2"], a["usable_m2"] + b["usable_m2"]
    return {"a": a, "b": b, "fraction": fraction, "net_area_m2": area, "usable_m2": usable,
            "built_up_m2": a["built_up_m2"] + b["built_up_m2"],
            "lost_percent": (1 - usable / area) * 100 if area else 0}


def utilization(site: Site, costs: Costs | None = None):
    plan = feasibility(site)
    if plan["status"] != "computed":
        return plan
    messages = [
        "Sensitivity curves are hypothetical net-area plots with highest available Table III bands, not changes to your current selected height or room layout.",
        "Curve samples: 50–5,000 yd² net area, 91 logarithmic samples per aspect ratio. Narrow-road widening is not deducted twice from those net areas.",
        "Split scenarios use gross frontage/depth and independently apply widening and Table III bands to each half. Splits do not apply TDR or compounding, matching the incumbent comparator.",
        "A sampled best split is not a global optimum or subdivision approval. Both resulting plots must retain direct frontage and independently satisfy access and permission rules.",
    ]
    if site.custom_setbacks:
        messages.append("Custom setbacks are applied independently to every sample and split half. Review their required/applied setback columns; any below-minimum result is non-compliant, not an approval.")
    series = []
    for aspect in (.75, .8, .875, .929, 1, 1.1, 1.167, 1.25, 2):
        samples = []
        for index in range(91):
            area = 50 * 100 ** (index / 90) * .83612736
            width = math.sqrt(area / aspect)
            sample = comparison_envelope(width, width * aspect, site.roads[plan["front"]], site, deduct_widening=False, sensitivity=True)
            sample["sample_area_m2"] = area
            sample["inr_per_built_ft2"] = None
            if costs is not None and all(getattr(costs, key) is not None for key in
                    ("land_inr_m2", "land_sro_inr_m2", "construction_inr_m2", "registration_percent", "gst_percent")):
                if not site.stilt or costs.stilt_inr_m2 is not None or costs.stilt_rate_mode == "legacy-55-percent":
                    ready = costs.estimate_scope == "partial" or (
                        costs.lrs_mode is not None and (costs.lrs_mode != "due" or costs.lrs_rebate is not None))
                    if ready:
                        # Narrow-road limits and user floor caps remain those in the original comparator.
                        fp, built = sample["usable_m2"], sample["built_up_m2"]
                        stilt_rate = costs.stilt_inr_m2 if costs.stilt_rate_mode == "explicit" else math.floor(costs.construction_inr_m2 * .09290304 * .55 + .5) / .09290304
                        construction = built * costs.construction_inr_m2 + (fp * stilt_rate if site.stilt else 0)
                        total = area * (costs.land_inr_m2 + costs.land_sro_inr_m2 * costs.registration_percent / 100) + construction * (1 + costs.gst_percent / 100)
                        if costs.estimate_scope == "legacy-schedule":
                            charges = schedule_charges(site, costs.model_copy(update={"brs_mode": "na"}), {
                                "gross_area_m2": area, "floors": sample["floors"],
                                "compounding_gain_m2": sample["compounding_gain_m2"],
                                "compounding_active": site.compounding and not site.custom_setbacks,
                            }, fp, built, construction)
                            total += sum(charges["lines_inr"].values())
                        sample["inr_per_built_ft2"] = total * .09290304 / built if built > 0 else None
            samples.append(sample)
        series.append({"aspect": aspect, "samples": samples})
    split = None
    if site.split_edge is not None:
        if site.split_edge not in site.facing or site.roads[site.split_edge] is None or site.split_fraction is None:
            messages.append("Split prerequisites: choose an abutting road and a 15–85% split fraction.")
        else:
            gross = plan["gross"]
            frontage, depth = (gross["width"], gross["depth"]) if site.split_edge in "NS" else (gross["depth"], gross["width"])
            road = site.roads[site.split_edge]
            selected = split_pair(frontage, depth, site.split_fraction, road, site)
            best = None
            for index in range(281):
                candidate = split_pair(frontage, depth, .15 + index * .0025, road, site)
                if best is None or candidate["usable_m2"] > best["usable_m2"] + 1e-9:
                    best = candidate
            split = {"edge": site.split_edge, "whole": comparison_envelope(frontage, depth, road, site),
                     "selected": selected, "best_sampled": best, "sample_count": 281}
    messages.append("Cost curves use the selected partial/retained schedule, exclude BRS and onward-sale duty, and leave missing-rate samples unknown. TDR purchase/permit fees remain excluded.")
    return {"status": "computed", "non_compliant": plan["non_compliant"],
            "net_area_m2": plan["net_area_m2"], "usable_m2": plan["usable_m2"],
            "coverage_percent": plan["coverage_percent"], "lost_percent": plan["lost_percent"],
            "built_up_m2": plan["built_up_m2"], "built_up_per_net_m2": plan["built_up_m2"] / plan["net_area_m2"],
            "series": series, "split": split, "messages": messages}
